# .github/workflows/deploy.yml
name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Trigger on pushes to the 'main' branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # Use a Linux runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 # Check out your repository code

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Specify Node.js version (adjust as needed)

      - name: Install Dependencies
        run: npm install --legacy-peer-deps # Or 'yarn install' if you use Yarn

      - name: Build Project
        run: npm run build # Or 'yarn build'. This creates your production build (e.g., 'build' or 'dist' folder)

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3 # Action to deploy to gh-pages
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # GitHub's built-in token
          publish_dir: ./dist # The directory containing your built static files (e.g., 'build', 'dist', 'public')
          publish_branch: gh-pages # The branch to publish to (create if it doesn't exist)
          cname: neuros.care
          # For project pages, ensure your 'homepage' in package.json is set correctly.
          # For user/organization pages, set publish_dir to the root of your main branch,
          # and change publish_branch to 'main' if you want to serve from main.
